/**
 * Wall configuration format:
 *   groups: array of X groups, each with:
 *     id:    unique string
 *     name:  display name shown when group is completed
 *     items: array of X strings (one per tile)
 */

export const testConfig = {
  groups: [
    {
      id: 'elements',
      name: 'Chemical Elements',
      items: [
        'Hydrogen', 'Helium', 'Lithium', 'Beryllium', 'Boron',
        'Carbon', 'Nitrogen', 'Oxygen', 'Fluorine', 'Neon',
        'Sodium', 'Magnesium', 'Aluminium', 'Silicon', 'Phosphorus',
        'Sulfur', 'Chlorine', 'Argon', 'Potassium', 'Calcium',
        'Scandium', 'Titanium', 'Vanadium', 'Chromium', 'Manganese',
        'Iron', 'Cobalt', 'Nickel', 'Copper', 'Zinc',
        'Gallium', 'Germanium', 'Arsenic', 'Selenium', 'Bromine',
        'Krypton', 'Rubidium', 'Strontium', 'Yttrium', 'Zirconium',
        'Niobium', 'Molybdenum', 'Technetium', 'Ruthenium', 'Rhodium',
      ],
    },
    {
      id: 'europe',
      name: 'European Countries',
      items: [
        'Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium',
        'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic',
        'Denmark', 'Estonia', 'Finland', 'France', 'Germany',
        'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy',
        'Kosovo', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg',
        'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands',
        'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania',
        'Russia', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia',
        'Spain', 'Sweden', 'Switzerland', 'Ukraine', 'Vatican City',
      ],
    },
    {
      id: 'usstates',
      name: 'US States',
      items: [
        'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
        'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
        'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
        'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
        'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
        'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
        'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
        'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
        'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
      ],
    },
    {
      id: 'capitals',
      name: 'World Capitals',
      items: [
        'Kabul', 'Tirana', 'Algiers', 'Andorra la Vella', 'Luanda',
        'Buenos Aires', 'Yerevan', 'Canberra', 'Vienna', 'Baku',
        'Nassau', 'Manama', 'Dhaka', 'Bridgetown', 'Minsk',
        'Brussels', 'Belmopan', 'Porto-Novo', 'Thimphu', 'Sucre',
        'Sarajevo', 'Gaborone', 'Brasília', 'Bandar Seri Begawan', 'Sofia',
        'Ouagadougou', 'Naypyidaw', 'Bujumbura', 'Phnom Penh', 'Yaoundé',
        'Ottawa', 'Praia', 'Bangui', "N'Djamena", 'Santiago',
        'Beijing', 'Bogotá', 'Moroni', 'Kinshasa', 'Brazzaville',
        'San José', 'Zagreb', 'Havana', 'Nicosia', 'Prague',
      ],
    },
    {
      id: 'proglangs',
      name: 'Programming Languages',
      items: [
        'Python', 'JavaScript', 'TypeScript', 'Java', 'C',
        'C++', 'C#', 'Ruby', 'Go', 'Rust',
        'Swift', 'Kotlin', 'PHP', 'R', 'MATLAB',
        'Perl', 'Scala', 'Haskell', 'Lua', 'Julia',
        'Dart', 'Elixir', 'Erlang', 'Clojure', 'F#',
        'Fortran', 'COBOL', 'Assembly', 'Pascal', 'Delphi',
        'Visual Basic', 'PowerShell', 'Bash', 'SQL', 'GraphQL',
        'Solidity', 'VHDL', 'Verilog', 'Ada', 'Prolog',
        'Lisp', 'Scheme', 'ML', 'OCaml', 'Racket',
      ],
    },
    {
      id: 'dogs',
      name: 'Dog Breeds',
      items: [
        'Labrador', 'Golden Retriever', 'German Shepherd', 'Bulldog', 'Poodle',
        'Beagle', 'Rottweiler', 'Yorkshire Terrier', 'Boxer', 'Dachshund',
        'Shih Tzu', 'Husky', 'Dobermann', 'Great Dane', 'Chihuahua',
        'Border Collie', 'Springer Spaniel', 'Cocker Spaniel', 'Maltese', 'Pomeranian',
        'Dalmatian', 'Saint Bernard', 'Basset Hound', 'Weimaraner', 'Vizsla',
        'Greyhound', 'Whippet', 'Samoyed', 'Akita', 'Shiba Inu',
        'Corgi', 'Bichon Frise', 'Schnauzer', 'Pug', 'Bloodhound',
        'Mastiff', 'Afghan Hound', 'Chow Chow', 'Newfoundland', 'Irish Setter',
        'Cavalier King Charles', 'Jack Russell', 'Miniature Pinscher', 'Papillon', 'Pointer',
      ],
    },
    {
      id: 'novels',
      name: 'Famous Novels',
      items: [
        'Pride and Prejudice', '1984', 'To Kill a Mockingbird', 'The Great Gatsby', 'Moby Dick',
        'War and Peace', 'Anna Karenina', 'Crime and Punishment', 'The Brothers Karamazov', 'Don Quixote',
        'Ulysses', 'One Hundred Years of Solitude', 'Brave New World', 'The Catcher in the Rye', 'Lord of the Flies',
        'Animal Farm', 'Fahrenheit 451', "The Hitchhiker's Guide to the Galaxy", 'Dune', 'The Lord of the Rings',
        'Harry Potter', 'A Tale of Two Cities', 'Oliver Twist', 'Jane Eyre', 'Wuthering Heights',
        'Middlemarch', 'Frankenstein', 'Dracula', 'The Picture of Dorian Gray', 'Treasure Island',
        'Robinson Crusoe', "Gulliver's Travels", 'The Call of the Wild', 'The Old Man and the Sea', 'Of Mice and Men',
        'East of Eden', 'The Grapes of Wrath', 'Catch-22', 'Slaughterhouse-Five', 'The Sun Also Rises',
        'For Whom the Bell Tolls', 'Heart of Darkness', 'Things Fall Apart', 'The Road', 'Never Let Me Go',
      ],
    },
    {
      id: 'greekgods',
      name: 'Greek Gods & Titans',
      items: [
        'Zeus', 'Hera', 'Poseidon', 'Demeter', 'Athena',
        'Apollo', 'Artemis', 'Ares', 'Aphrodite', 'Hephaestus',
        'Hermes', 'Dionysus', 'Hades', 'Persephone', 'Hestia',
        'Eros', 'Nike', 'Iris', 'Hecate', 'Morpheus',
        'Thanatos', 'Hypnos', 'Nemesis', 'Tyche', 'Eris',
        'Prometheus', 'Epimetheus', 'Atlas', 'Cronus', 'Rhea',
        'Gaia', 'Uranus', 'Hyperion', 'Helios', 'Selene',
        'Eos', 'Mnemosyne', 'Themis', 'Oceanus', 'Tethys',
        'Nyx', 'Erebus', 'Tartarus', 'Pontus', 'Aether',
      ],
    },
    {
      id: 'cheese',
      name: 'Types of Cheese',
      items: [
        'Cheddar', 'Brie', 'Camembert', 'Gouda', 'Edam',
        'Stilton', 'Gorgonzola', 'Roquefort', 'Parmesan', 'Mozzarella',
        'Ricotta', 'Feta', 'Gruyère', 'Emmental', 'Manchego',
        'Pecorino', 'Provolone', 'Fontina', 'Taleggio', 'Burrata',
        'Halloumi', 'Paneer', 'Queso Fresco', 'Monterey Jack', 'Colby',
        'Swiss', 'Havarti', 'Muenster', 'Limburger', 'Raclette',
        'Comté', 'Beaufort', 'Époisses', 'Livarot', "Pont-l'Évêque",
        'Reblochon', 'Vacherin', 'Appenzeller', 'Jarlsberg', 'Danbo',
        'Maasdam', 'Samsoe', 'Tilsit', 'Lancashire', 'Wensleydale',
      ],
    },
    {
      id: 'pasta',
      name: 'Types of Pasta',
      items: [
        'Spaghetti', 'Penne', 'Rigatoni', 'Fusilli', 'Farfalle',
        'Linguine', 'Fettuccine', 'Tagliatelle', 'Pappardelle', 'Lasagne',
        'Cannelloni', 'Manicotti', 'Conchiglie', 'Orecchiette', 'Cavatappi',
        'Rotini', 'Gemelli', 'Tortiglioni', 'Bucatini', 'Vermicelli',
        'Capellini', 'Mafaldine', 'Paccheri', 'Ziti', 'Ditali',
        'Macaroni', 'Acini di Pepe', 'Orzo', 'Pastina', 'Stelline',
        'Ruote', 'Radiatori', 'Trofie', 'Strozzapreti', 'Casarecce',
        'Maltagliati', 'Pizzoccheri', 'Bigoli', 'Chitarra', 'Pici',
        'Calamarata', 'Soba', 'Udon', 'Ramen', 'Somen',
      ],
    },
    {
      id: 'cocktails',
      name: 'Cocktails',
      items: [
        'Martini', 'Mojito', 'Old Fashioned', 'Manhattan', 'Cosmopolitan',
        'Negroni', 'Daiquiri', 'Margarita', 'Piña Colada', 'Whiskey Sour',
        'Aperol Spritz', 'Bellini', 'Mimosa', 'Bloody Mary', 'Tom Collins',
        'Gin and Tonic', 'Long Island Iced Tea', 'Singapore Sling', 'Harvey Wallbanger', 'Sex on the Beach',
        'Tequila Sunrise', 'Blue Lagoon', 'Kir Royale', 'French 75', 'Sidecar',
        'White Russian', 'Black Russian', 'Screwdriver', 'Champagne Cocktail', 'Americano',
        'Espresso Martini', 'Porn Star Martini', 'Clover Club', 'Gimlet', 'Aviation',
        'Last Word', 'Corpse Reviver', 'Paper Plane', "Bee's Knees", 'Dark and Stormy',
        'Moscow Mule', 'Paloma', 'Caipirinha', 'Sazerac', 'Penicillin',
      ],
    },
    {
      id: 'sharks',
      name: 'Types of Shark',
      items: [
        'Great White', 'Hammerhead', 'Tiger', 'Bull', 'Mako',
        'Whale', 'Nurse', 'Lemon', 'Blue', 'Blacktip',
        'Whitetip', 'Reef', 'Thresher', 'Sand Tiger', 'Wobbegong',
        'Horn', 'Port Jackson', 'Zebra', 'Leopard', 'Angel',
        'Sawshark', 'Frilled', 'Goblin', 'Megamouth', 'Cookiecutter',
        'Dwarf Lanternshark', 'Velvet Belly Lanternshark', 'Cat', 'Swell', 'Bamboo',
        'Brownbanded Bamboo', 'Epaulette', 'Tasselled Wobbegong', 'Banded Wobbegong', 'Spotted Wobbegong',
        'Shortfin Mako', 'Longfin Mako', 'Porbeagle', 'Salmon', 'Spiny Dogfish',
        'Smooth Dogfish', 'Spinner', 'Silvertip', 'Silky', 'Scalloped Hammerhead',
      ],
    },
    {
      id: 'painters',
      name: 'Famous Painters',
      items: [
        'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Rembrandt', 'Vermeer',
        'Monet', 'Manet', 'Renoir', 'Degas', 'Cézanne',
        'Van Gogh', 'Gauguin', 'Seurat', 'Matisse', 'Picasso',
        'Braque', 'Duchamp', 'Mondrian', 'Kandinsky', 'Klee',
        'Dalí', 'Miró', 'Magritte', 'Ernst', 'Klimt',
        'Schiele', 'Munch', 'Kirchner', 'Beckmann', 'Hopper',
        "O'Keeffe", 'Pollock', 'Rothko', 'de Kooning', 'Warhol',
        'Lichtenstein', 'Hockney', 'Bacon', 'Freud', 'Hirst',
        'Banksy', 'Basquiat', 'Koons', 'Kahlo', 'Rivera',
      ],
    },
    {
      id: 'olympics',
      name: 'Olympic Sports',
      items: [
        'Athletics', 'Swimming', 'Gymnastics', 'Cycling', 'Rowing',
        'Canoeing', 'Weightlifting', 'Wrestling', 'Judo', 'Boxing',
        'Fencing', 'Shooting', 'Archery', 'Equestrian', 'Sailing',
        'Triathlon', 'Modern Pentathlon', 'Badminton', 'Tennis', 'Table Tennis',
        'Volleyball', 'Basketball', 'Football', 'Hockey', 'Handball',
        'Water Polo', 'Diving', 'Marathon Swimming', 'Skateboarding', 'Surfing',
        'Sport Climbing', 'Karate', 'Taekwondo', 'Golf', 'Rugby Sevens',
        'Beach Volleyball', 'BMX Racing', 'BMX Freestyle', 'Mountain Biking', 'Track Cycling',
        'Road Cycling', 'Biathlon', 'Cross-Country Skiing', 'Curling', 'Ski Jumping',
      ],
    },
    {
      id: 'dance',
      name: 'Types of Dance',
      items: [
        'Ballet', 'Waltz', 'Tango', 'Foxtrot', 'Quickstep',
        'Viennese Waltz', 'Cha-Cha', 'Samba', 'Rumba', 'Paso Doble',
        'Jive', 'Salsa', 'Merengue', 'Bachata', 'Swing',
        'Lindy Hop', 'Charleston', 'Tap', 'Jazz', 'Contemporary',
        'Modern', 'Flamenco', 'Bollywood', 'Bhangra', 'Kathak',
        'Bharatanatyam', 'Odissi', 'Hip Hop', 'Breakdancing', 'Popping',
        'Locking', 'Krump', 'Voguing', 'Irish Step', 'Highland',
        'Morris', 'Ceilidh', 'Polka', 'Mazurka', 'Minuet',
        'Gavotte', 'Pavane', 'Galliard', 'Sarabande', 'Gigue',
      ],
    },
    {
      id: 'instruments',
      name: 'Musical Instruments',
      items: [
        'Piano', 'Violin', 'Viola', 'Cello', 'Double Bass',
        'Guitar', 'Bass Guitar', 'Ukulele', 'Banjo', 'Mandolin',
        'Harp', 'Lute', 'Sitar', 'Koto', 'Erhu',
        'Trumpet', 'Trombone', 'French Horn', 'Tuba', 'Flugelhorn',
        'Flute', 'Piccolo', 'Oboe', 'Clarinet', 'Bassoon',
        'Saxophone', 'Recorder', 'Bagpipes', 'Harmonica', 'Accordion',
        'Concertina', 'Drums', 'Snare Drum', 'Bass Drum', 'Timpani',
        'Xylophone', 'Marimba', 'Vibraphone', 'Glockenspiel', 'Theremin',
        'Synthesizer', 'Organ', 'Harpsichord', 'Dulcimer', 'Zither',
      ],
    },
    {
      id: 'constellations',
      name: 'Constellations',
      items: [
        'Orion', 'Ursa Major', 'Ursa Minor', 'Cassiopeia', 'Perseus',
        'Andromeda', 'Pegasus', 'Cygnus', 'Aquila', 'Lyra',
        'Hercules', 'Draco', 'Leo', 'Virgo', 'Scorpius',
        'Sagittarius', 'Capricornus', 'Aquarius', 'Pisces', 'Aries',
        'Taurus', 'Gemini', 'Cancer', 'Libra', 'Ophiuchus',
        'Serpens', 'Canis Major', 'Canis Minor', 'Lepus', 'Eridanus',
        'Boötes', 'Corona Borealis', 'Corvus', 'Crater', 'Hydra',
        'Centaurus', 'Lupus', 'Ara', 'Triangulum', 'Auriga',
        'Canes Venatici', 'Coma Berenices', 'Vulpecula', 'Sagitta', 'Delphinus',
      ],
    },
    {
      id: 'rivers',
      name: 'Rivers',
      items: [
        'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'Yenisei',
        'Yellow River', 'Ob', 'Congo', 'Amur', 'Lena',
        'Mekong', 'Irtysh', 'Niger', 'Zambezi', 'Murray',
        'Volga', 'Indus', 'Ganges', 'Brahmaputra', 'Danube',
        'Rhine', 'Loire', 'Thames', 'Seine', 'Elbe',
        'Oder', 'Vistula', 'Don', 'Dnieper', 'Ural',
        'Colorado', 'Columbia', 'Rio Grande', 'Missouri', 'Ohio',
        'Arkansas', 'Tennessee', 'Hudson', 'Potomac', 'Yukon',
        'Mackenzie', 'Fraser', 'Euphrates', 'Tigris', 'Jordan',
      ],
    },
    {
      id: 'mountains',
      name: 'Mountains',
      items: [
        'Everest', 'K2', 'Kangchenjunga', 'Lhotse', 'Makalu',
        'Cho Oyu', 'Dhaulagiri', 'Manaslu', 'Nanga Parbat', 'Annapurna',
        'Gasherbrum I', 'Broad Peak', 'Gasherbrum II', 'Shishapangma', 'Gyachung Kang',
        'Himalchuli', 'Distaghil Sar', 'Ngadi Chuli', 'Nuptse', 'Khunyang Chhish',
        'Masherbrum', 'Rakaposhi', 'Batura Sar', 'Kanjut Sar', 'Saltoro Kangri',
        'Trivor', 'Kangbachen', 'Jannu', 'Molamenqing', 'Kongur',
        'Tirich Mir', 'Saser Kangri', 'Chogolisa', 'Dhaulagiri II', 'Gurla Mandhata',
        'Muztagh', 'Skil Brum', 'Malubiting', 'Lhotse Shar', 'Chamlang',
        'Baruntse', 'Abi Gamin', 'Ghent Kangri', 'Istor-o-Nal', 'Yukshin Gardan Sar',
      ],
    },
    {
      id: 'currencies',
      name: 'Currencies',
      items: [
        'Dollar', 'Euro', 'Pound', 'Yen', 'Yuan',
        'Rupee', 'Ruble', 'Won', 'Franc', 'Krona',
        'Krone', 'Forint', 'Zloty', 'Lira', 'Peso',
        'Real', 'Rand', 'Dirham', 'Riyal', 'Dinar',
        'Baht', 'Ringgit', 'Rupiah', 'Dong', 'Hryvnia',
        'Tenge', 'Som', 'Manat', 'Lari', 'Dram',
        'Lev', 'Kuna', 'Koruna', 'Shekel', 'Birr',
        'Shilling', 'Naira', 'Cedi', 'Dalasi', 'Leone',
        'Kwacha', 'Pula', 'Lilangeni', 'Togrog', 'Taka',
      ],
    },
    {
      id: 'worldlangs',
      name: 'World Languages',
      items: [
        'Mandarin', 'Spanish', 'English', 'Hindi', 'Arabic',
        'Bengali', 'Portuguese', 'Russian', 'Japanese', 'Punjabi',
        'Marathi', 'Telugu', 'Wu Chinese', 'Turkish', 'Korean',
        'French', 'German', 'Vietnamese', 'Tamil', 'Urdu',
        'Javanese', 'Italian', 'Gujarati', 'Persian', 'Hausa',
        'Kannada', 'Indonesian', 'Polish', 'Yoruba', 'Xhosa',
        'Malayalam', 'Odia', 'Burmese', 'Sundanese', 'Amharic',
        'Zulu', 'Igbo', 'Ukrainian', 'Romanian', 'Dutch',
        'Greek', 'Hungarian', 'Czech', 'Swedish', 'Finnish',
      ],
    },
    {
      id: 'wine',
      name: 'Wine Varieties',
      items: [
        'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Syrah', 'Grenache',
        'Malbec', 'Tempranillo', 'Sangiovese', 'Nebbiolo', 'Barbera',
        'Dolcetto', 'Montepulciano', 'Zinfandel', 'Petit Verdot', 'Mourvèdre',
        'Carignan', 'Cinsault', 'Gamay', 'Pinotage', 'Primitivo',
        'Chardonnay', 'Sauvignon Blanc', 'Riesling', 'Pinot Grigio', 'Chenin Blanc',
        'Viognier', 'Gewurztraminer', 'Albariño', 'Verdejo', 'Grüner Veltliner',
        'Torrontés', 'Moscato', 'Marsanne', 'Roussanne', 'Semillon',
        'Furmint', 'Trebbiano', 'Vermentino', 'Cortese', 'Gavi',
        'Soave', 'Prosecco', 'Cava', 'Champagne', 'Crémant',
      ],
    },
    {
      id: 'boardgames',
      name: 'Board Games',
      items: [
        'Chess', 'Checkers', 'Backgammon', 'Go', 'Monopoly',
        'Scrabble', 'Risk', 'Cluedo', 'Trivial Pursuit', 'Battleship',
        'Connect Four', 'Othello', 'Boggle', 'Pictionary', 'Taboo',
        'Cranium', 'Articulate', 'Balderdash', 'Jenga', 'Twister',
        'Sorry', 'Snakes and Ladders', 'Ludo', 'Mahjong', 'Dominoes',
        'Yahtzee', 'Bingo', 'Rummy', 'Catan', 'Ticket to Ride',
        'Pandemic', 'Carcassonne', 'Agricola', 'Puerto Rico', 'Power Grid',
        'Terraforming Mars', 'Spirit Island', 'Wingspan', 'Azul', 'Codenames',
        'Dixit', 'Hanabi', 'Coup', 'Love Letter', '7 Wonders',
      ],
    },
    {
      id: 'africa',
      name: 'African Countries',
      items: [
        'Nigeria', 'Ethiopia', 'Egypt', 'DR Congo', 'Tanzania',
        'South Africa', 'Kenya', 'Uganda', 'Algeria', 'Sudan',
        'Morocco', 'Angola', 'Mozambique', 'Ghana', 'Madagascar',
        'Cameroon', "Côte d'Ivoire", 'Niger', 'Burkina Faso', 'Mali',
        'Malawi', 'Zambia', 'Senegal', 'Chad', 'Somalia',
        'Zimbabwe', 'Guinea', 'Rwanda', 'Benin', 'Burundi',
        'Tunisia', 'South Sudan', 'Togo', 'Sierra Leone', 'Libya',
        'Congo', 'Liberia', 'Mauritania', 'Eritrea', 'Namibia',
        'Gambia', 'Botswana', 'Gabon', 'Lesotho', 'Equatorial Guinea',
      ],
    },
    {
      id: 'dinosaurs',
      name: 'Types of Dinosaur',
      items: [
        'Tyrannosaurus', 'Triceratops', 'Velociraptor', 'Brachiosaurus', 'Ankylosaurus',
        'Stegosaurus', 'Diplodocus', 'Allosaurus', 'Spinosaurus', 'Parasaurolophus',
        'Iguanodon', 'Pachycephalosaurus', 'Gallimimus', 'Dilophosaurus', 'Carnotaurus',
        'Ceratosaurus', 'Megalosaurus', 'Baryonyx', 'Suchomimus', 'Giganotosaurus',
        'Carcharodontosaurus', 'Albertosaurus', 'Daspletosaurus', 'Torvosaurus', 'Saurophaganax',
        'Acrocanthosaurus', 'Euoplocephalus', 'Kentrosaurus', 'Edmontonia', 'Polacanthus',
        'Scelidosaurus', 'Ouranosaurus', 'Maiasaura', 'Lambeosaurus', 'Corythosaurus',
        'Saurolophus', 'Edmontosaurus', 'Shantungosaurus', 'Tsintaosaurus', 'Hypacrosaurus',
        'Bactrosaurus', 'Hadrosaurus', 'Therizinosaurus', 'Oviraptor', 'Protoceratops',
      ],
    },
    {
      id: 'scientists',
      name: 'Famous Scientists',
      items: [
        'Isaac Newton', 'Albert Einstein', 'Charles Darwin', 'Marie Curie', 'Galileo Galilei',
        'Nikola Tesla', 'Stephen Hawking', 'Richard Feynman', 'Niels Bohr', 'Max Planck',
        'Werner Heisenberg', 'Erwin Schrödinger', 'Paul Dirac', 'James Clerk Maxwell', 'Michael Faraday',
        'Humphry Davy', 'Antoine Lavoisier', 'John Dalton', 'Dmitri Mendeleev', 'Louis Pasteur',
        'Robert Koch', 'Alexander Fleming', 'Francis Crick', 'James Watson', 'Rosalind Franklin',
        'Gregor Mendel', 'Carl Linnaeus', 'Alfred Wallace', 'Ernst Haeckel', 'Thomas Huxley',
        'William Harvey', 'Andreas Vesalius', 'Carl Gauss', 'Leonhard Euler', 'Bernhard Riemann',
        'Henri Poincaré', 'David Hilbert', 'Kurt Gödel', 'Alan Turing', 'John von Neumann',
        'Claude Shannon', 'Norbert Wiener', 'Lise Meitner', 'Ada Lovelace', 'Archimedes',
      ],
    },
    {
      id: 'ukcounties',
      name: 'UK Counties',
      items: [
        'Kent', 'Surrey', 'Essex', 'Suffolk', 'Norfolk',
        'Cambridgeshire', 'Hertfordshire', 'Bedfordshire', 'Buckinghamshire', 'Oxfordshire',
        'Berkshire', 'Hampshire', 'West Sussex', 'East Sussex', 'Wiltshire',
        'Dorset', 'Somerset', 'Devon', 'Cornwall', 'Gloucestershire',
        'Worcestershire', 'Herefordshire', 'Shropshire', 'Staffordshire', 'Derbyshire',
        'Nottinghamshire', 'Leicestershire', 'Northamptonshire', 'Warwickshire', 'West Midlands',
        'Cheshire', 'Lancashire', 'Durham', 'Northumberland', 'Cumbria',
        'Lincolnshire', 'Rutland', 'Merseyside', 'Greater Manchester', 'South Yorkshire',
        'West Yorkshire', 'North Yorkshire', 'Tyne and Wear', 'Cleveland', 'Avon',
      ],
    },
    {
      id: 'writers',
      name: 'Famous Writers',
      items: [
        'William Shakespeare', 'Charles Dickens', 'Jane Austen', 'Leo Tolstoy', 'Fyodor Dostoevsky',
        'Franz Kafka', 'James Joyce', 'Virginia Woolf', 'Marcel Proust', 'Gabriel García Márquez',
        'Jorge Luis Borges', 'Ernest Hemingway', 'F. Scott Fitzgerald', 'William Faulkner', 'John Steinbeck',
        'Toni Morrison', 'Salman Rushdie', 'Kazuo Ishiguro', 'Haruki Murakami', 'Chinua Achebe',
        'Wole Soyinka', 'Naguib Mahfouz', 'Günter Grass', 'Thomas Mann', 'Hermann Hesse',
        'Bertolt Brecht', 'Stefan Zweig', 'Joseph Roth', 'Arthur Schnitzler', 'Peter Handke',
        'Elfriede Jelinek', 'Ingeborg Bachmann', 'Rainer Maria Rilke', 'Patrick White', 'Doris Lessing',
        'Nadine Gordimer', 'J.M. Coetzee', 'Albert Camus', 'Jean-Paul Sartre', 'Simone de Beauvoir',
        'Samuel Beckett', 'Harold Pinter', 'Tom Stoppard', 'Arthur Miller', 'Tennessee Williams',
      ],
    },
    {
      id: 'directors',
      name: 'Film Directors',
      items: [
        'Alfred Hitchcock', 'Stanley Kubrick', 'Orson Welles', 'Federico Fellini', 'Ingmar Bergman',
        'Akira Kurosawa', 'Jean-Luc Godard', 'François Truffaut', 'Martin Scorsese', 'Francis Ford Coppola',
        'Steven Spielberg', 'George Lucas', 'Ridley Scott', 'James Cameron', 'Christopher Nolan',
        'Quentin Tarantino', 'Tim Burton', 'David Lynch', 'David Fincher', 'Paul Thomas Anderson',
        'Wes Anderson', 'Sofia Coppola', 'Kathryn Bigelow', 'Greta Gerwig', 'Pedro Almodóvar',
        'Werner Herzog', 'Wim Wenders', 'Rainer Werner Fassbinder', 'Bernardo Bertolucci', 'Michelangelo Antonioni',
        'Luchino Visconti', 'Roberto Rossellini', 'Jean Renoir', 'Robert Bresson', 'Jacques Tati',
        'Claude Chabrol', 'Louis Malle', 'Eric Rohmer', 'Alain Resnais', 'Agnès Varda',
        'Yasujiro Ozu', 'Kenji Mizoguchi', 'Satyajit Ray', 'Abbas Kiarostami', 'Zhang Yimou',
      ],
    },
    {
      id: 'gems',
      name: 'Gemstones',
      items: [
        'Diamond', 'Ruby', 'Emerald', 'Sapphire', 'Amethyst',
        'Topaz', 'Opal', 'Pearl', 'Garnet', 'Turquoise',
        'Jade', 'Aquamarine', 'Alexandrite', 'Tanzanite', 'Tourmaline',
        'Spinel', 'Peridot', 'Citrine', 'Amber', 'Coral',
        'Lapis Lazuli', 'Malachite', 'Moonstone', 'Sunstone', 'Labradorite',
        'Amazonite', 'Rhodonite', 'Rhodochrosite', 'Chrysoprase', 'Onyx',
        'Agate', 'Jasper', 'Bloodstone', 'Carnelian', 'Chalcedony',
        'Rose Quartz', 'Smoky Quartz', 'Rutilated Quartz', 'Ametrine', 'Kunzite',
        'Morganite', 'Heliodor', 'Goshenite', 'Bixbite', 'Zircon',
      ],
    },
    {
      id: 'trees',
      name: 'Types of Tree',
      items: [
        'Oak', 'Ash', 'Beech', 'Birch', 'Elm',
        'Maple', 'Chestnut', 'Walnut', 'Cherry', 'Apple',
        'Pear', 'Plum', 'Willow', 'Poplar', 'Alder',
        'Hazel', 'Hornbeam', 'Sycamore', 'Lime', 'Rowan',
        'Horse Chestnut', 'Field Maple', 'Crab Apple', 'Scots Pine', 'Norway Spruce',
        'Silver Fir', 'Douglas Fir', 'Larch', 'Cedar', 'Yew',
        'Holly', 'Box', 'Hawthorn', 'Blackthorn', 'Elder',
        'Spindle', 'Guelder Rose', 'Dogwood', 'Wayfaring Tree', 'Juniper',
        'Lawson Cypress', 'Leyland Cypress', 'Western Red Cedar', 'Dawn Redwood', 'Monkey Puzzle',
      ],
    },
    {
      id: 'composers',
      name: 'Famous Composers',
      items: [
        'Bach', 'Handel', 'Vivaldi', 'Telemann', 'Scarlatti',
        'Haydn', 'Mozart', 'Beethoven', 'Schubert', 'Schumann',
        'Chopin', 'Liszt', 'Brahms', 'Wagner', 'Verdi',
        'Puccini', 'Bizet', 'Berlioz', 'Saint-Saëns', 'Debussy',
        'Ravel', 'Fauré', 'Satie', 'Franck', 'Mahler',
        'Bruckner', 'Strauss', 'Dvořák', 'Janáček', 'Smetana',
        'Sibelius', 'Grieg', 'Elgar', 'Vaughan Williams', 'Britten',
        'Holst', 'Delius', 'Walton', 'Stravinsky', 'Prokofiev',
        'Shostakovich', 'Rachmaninoff', 'Scriabin', 'Rimsky-Korsakov', 'Bartók',
      ],
    },
    {
      id: 'football',
      name: 'Football Clubs',
      items: [
        'Real Madrid', 'Barcelona', 'Manchester United', 'Liverpool', 'Manchester City',
        'Arsenal', 'Chelsea', 'Tottenham', 'Juventus', 'AC Milan',
        'Inter Milan', 'Roma', 'Napoli', 'Bayern Munich', 'Borussia Dortmund',
        'Bayer Leverkusen', 'RB Leipzig', 'PSG', 'Lyon', 'Marseille',
        'Atletico Madrid', 'Sevilla', 'Valencia', 'Ajax', 'PSV',
        'Feyenoord', 'Benfica', 'Porto', 'Sporting CP', 'Celtic',
        'Rangers', 'Galatasaray', 'Fenerbahçe', 'Besiktas', 'Anderlecht',
        'Club Brugge', 'Red Star Belgrade', 'Dinamo Zagreb', 'Shakhtar Donetsk', 'Dynamo Kyiv',
        'Zenit', 'Spartak Moscow', 'Lokomotiv Moscow', 'Steaua Bucharest', 'Boavista',
      ],
    },
    {
      id: 'fish',
      name: 'Types of Fish',
      items: [
        'Salmon', 'Tuna', 'Cod', 'Halibut', 'Sea Bass',
        'Red Snapper', 'Mahi-mahi', 'Swordfish', 'Marlin', 'Barracuda',
        'Grouper', 'Snook', 'Tarpon', 'Bonefish', 'Flounder',
        'Sole', 'Plaice', 'Turbot', 'Brill', 'Monkfish',
        'Haddock', 'Pollock', 'Whiting', 'Mackerel', 'Herring',
        'Sardine', 'Anchovy', 'Sprat', 'Pike', 'Perch',
        'Zander', 'Walleye', 'Bass', 'Carp', 'Bream',
        'Tench', 'Chub', 'Roach', 'Rudd', 'Dace',
        'Barbel', 'Gudgeon', 'Bleak', 'Grayling', 'Trout',
      ],
    },
    {
      id: 'asia',
      name: 'Asian Countries',
      items: [
        'China', 'India', 'Indonesia', 'Pakistan', 'Bangladesh',
        'Japan', 'Philippines', 'Vietnam', 'Iran', 'Turkey',
        'Thailand', 'Myanmar', 'South Korea', 'Iraq', 'Afghanistan',
        'Saudi Arabia', 'Uzbekistan', 'Malaysia', 'Yemen', 'Nepal',
        'North Korea', 'Sri Lanka', 'Kazakhstan', 'Syria', 'Cambodia',
        'Jordan', 'Azerbaijan', 'UAE', 'Tajikistan', 'Israel',
        'Laos', 'Lebanon', 'Kyrgyzstan', 'Turkmenistan', 'Singapore',
        'Oman', 'Palestine', 'Kuwait', 'Georgia', 'Mongolia',
        'Armenia', 'Qatar', 'Bahrain', 'Timor-Leste', 'Maldives',
      ],
    },
    {
      id: 'snakes',
      name: 'Types of Snake',
      items: [
        'King Cobra', 'Black Mamba', 'Green Mamba', 'Boomslang', 'Inland Taipan',
        'Coastal Taipan', 'Eastern Brown', 'Western Brown', 'Tiger Snake', 'Death Adder',
        'Diamondback Rattlesnake', 'Timber Rattlesnake', 'Sidewinder', 'Copperhead', 'Cottonmouth',
        'Coral Snake', 'Boa Constrictor', 'Green Anaconda', 'Reticulated Python', 'Burmese Python',
        'Ball Python', 'Carpet Python', 'Corn Snake', 'King Snake', 'Milk Snake',
        'Hognose Snake', 'Garter Snake', 'Rat Snake', 'Indigo Snake', 'Rainbow Boa',
        'Emerald Tree Boa', 'Green Tree Python', 'Rough Green Snake', 'Smooth Snake', 'Grass Snake',
        'Common Viper', 'Horned Viper', 'Gaboon Viper', 'Puff Adder', 'Saw-Scaled Viper',
        'Sand Boa', 'Rubber Boa', 'Mud Snake', 'Rainbow Snake', 'Worm Snake',
      ],
    },
    {
      id: 'beer',
      name: 'Types of Beer',
      items: [
        'Lager', 'Pilsner', 'Pale Ale', 'India Pale Ale', 'Session IPA',
        'Double IPA', 'Stout', 'Porter', 'Milk Stout', 'Oatmeal Stout',
        'Imperial Stout', 'Brown Ale', 'Red Ale', 'Amber Ale', 'Wheat Beer',
        'Hefeweizen', 'Witbier', 'Saison', 'Farmhouse Ale', 'Gose',
        'Berliner Weisse', 'Kölsch', 'Altbier', 'Bock', 'Doppelbock',
        'Eisbock', 'Märzen', 'Dunkel', 'Schwarzbier', 'Rauchbier',
        'Smoked Beer', 'Fruit Beer', 'Sour Beer', 'Lambic', 'Gueuze',
        'Kriek', 'Flanders Red', 'Oud Bruin', 'Barleywine', 'Tripel',
        'Dubbel', 'Quadrupel', 'Belgian Strong', 'Cream Ale', 'Steam Beer',
      ],
    },
    {
      id: 'americas',
      name: 'Countries in the Americas',
      items: [
        'United States', 'Canada', 'Mexico', 'Guatemala', 'Belize',
        'Honduras', 'El Salvador', 'Nicaragua', 'Costa Rica', 'Panama',
        'Colombia', 'Venezuela', 'Guyana', 'Suriname', 'Brazil',
        'Ecuador', 'Peru', 'Bolivia', 'Paraguay', 'Uruguay',
        'Argentina', 'Chile', 'Cuba', 'Jamaica', 'Haiti',
        'Dominican Republic', 'Trinidad and Tobago', 'Barbados', 'Grenada', 'Saint Lucia',
        'Saint Vincent', 'Antigua and Barbuda', 'Dominica', 'Saint Kitts and Nevis', 'Bahamas',
        'Aruba', 'Curaçao', 'Cayman Islands', 'Turks and Caicos', 'Bermuda',
        'Puerto Rico', 'US Virgin Islands', 'British Virgin Islands', 'Martinique', 'Guadeloupe',
      ],
    },
    {
      id: 'spices',
      name: 'Spices & Herbs',
      items: [
        'Black Pepper', 'Cumin', 'Coriander', 'Turmeric', 'Paprika',
        'Cinnamon', 'Cloves', 'Cardamom', 'Nutmeg', 'Mace',
        'Allspice', 'Star Anise', 'Fennel', 'Anise', 'Caraway',
        'Fenugreek', 'Mustard', 'Ginger', 'Galangal', 'Lemongrass',
        'Bay Leaf', 'Rosemary', 'Thyme', 'Oregano', 'Basil',
        'Mint', 'Parsley', 'Chive', 'Dill', 'Tarragon',
        'Sage', 'Marjoram', 'Savory', 'Lovage', 'Sorrel',
        'Chervil', 'Borage', 'Lavender', 'Chamomile', 'Saffron',
        'Vanilla', 'Horseradish', 'Wasabi', 'Sumac', "Za'atar",
      ],
    },
    {
      id: 'butterflies',
      name: 'Types of Butterfly',
      items: [
        'Monarch', 'Painted Lady', 'Red Admiral', 'Peacock', 'Comma',
        'Small Tortoiseshell', 'Large Tortoiseshell', 'Brimstone', 'Cabbage White', 'Orange Tip',
        'Clouded Yellow', 'Adonis Blue', 'Common Blue', 'Holly Blue', 'Silver-Studded Blue',
        'Chalk Hill Blue', 'Large Blue', 'Purple Emperor', 'White Admiral', 'Camberwell Beauty',
        'Swallowtail', 'Scarce Swallowtail', 'Clouded Apollo', 'Apollo', 'Black-Veined White',
        'Bath White', 'Marbled White', 'Grayling', 'Meadow Brown', 'Gatekeeper',
        'Speckled Wood', 'Wall Brown', 'Ringlet', 'Scotch Argus', 'Mountain Ringlet',
        'Silver-Washed Fritillary', 'Dark Green Fritillary', 'High Brown Fritillary', 'Pearl-Bordered Fritillary', 'Marsh Fritillary',
        'Duke of Burgundy', 'Purple Hairstreak', 'Brown Hairstreak', 'Green Hairstreak', 'White-Letter Hairstreak',
      ],
    },
    {
      id: 'battles',
      name: 'Historical Battles',
      items: [
        'Battle of Marathon', 'Battle of Thermopylae', 'Battle of Salamis', 'Battle of Plataea', 'Battle of Gaugamela',
        'Battle of Cannae', 'Battle of Zama', 'Battle of Actium', 'Battle of Hastings', 'Battle of Crécy',
        'Battle of Agincourt', 'Battle of Bosworth Field', 'Battle of Lepanto', 'Battle of Armada', 'Battle of Breitenfeld',
        'Battle of Blenheim', 'Battle of Poltava', 'Battle of Plassey', 'Battle of Quebec', 'Battle of Saratoga',
        'Battle of Trafalgar', 'Battle of Austerlitz', 'Battle of Waterloo', 'Battle of Gettysburg', 'Battle of Sedan',
        'Battle of Tsushima', 'Battle of Ypres', 'Battle of the Somme', 'Battle of Verdun', 'Battle of Passchendaele',
        'Battle of the Marne', 'Battle of Jutland', 'Battle of Stalingrad', 'Battle of Kursk', 'Battle of Berlin',
        'Battle of Midway', 'Battle of Coral Sea', 'Battle of Guadalcanal', 'Battle of El Alamein', 'Battle of Monte Cassino',
        'Battle of Normandy', 'Battle of the Bulge', 'Battle of Iwo Jima', 'Battle of Okinawa', 'Battle of Dien Bien Phu',
      ],
    },
    {
      id: 'videogames',
      name: 'Video Games',
      items: [
        'Super Mario Bros', 'The Legend of Zelda', 'Minecraft', 'Tetris', 'Pac-Man',
        'Space Invaders', 'Pong', 'Doom', 'Quake', 'Half-Life',
        'Portal', 'Counter-Strike', 'Team Fortress 2', 'Left 4 Dead', 'BioShock',
        'System Shock', 'Deus Ex', 'Thief', 'Dishonored', 'Prey',
        'Halo', 'Gears of War', 'Mass Effect', 'Dragon Age', "Baldur's Gate",
        'Planescape Torment', 'Fallout', 'The Elder Scrolls', 'Dark Souls', 'Bloodborne',
        'Sekiro', 'Elden Ring', 'Final Fantasy', 'Dragon Quest', 'Chrono Trigger',
        'Metal Gear Solid', 'Resident Evil', 'Silent Hill', 'Castlevania', 'Mega Man',
        'Street Fighter', 'Mortal Kombat', 'Tekken', 'Fortnite', 'PUBG',
      ],
    },
    {
      id: 'genres',
      name: 'Musical Genres',
      items: [
        'Classical', 'Baroque', 'Romantic', 'Impressionist', 'Opera',
        'Jazz', 'Blues', 'Gospel', 'Soul', 'R&B',
        'Funk', 'Disco', 'Hip Hop', 'Rap', 'Electronic',
        'House', 'Techno', 'Trance', 'Drum and Bass', 'Dubstep',
        'Ambient', 'New Age', 'Folk', 'Country', 'Bluegrass',
        'Rockabilly', 'Rock', 'Classic Rock', 'Hard Rock', 'Heavy Metal',
        'Death Metal', 'Black Metal', 'Punk', 'Post-Punk', 'New Wave',
        'Alternative', 'Grunge', 'Indie', 'Pop', 'Reggae',
        'Ska', 'Dancehall', 'World Music', 'Latin', 'Bossa Nova',
      ],
    },
    {
      id: 'flowers',
      name: 'Types of Flower',
      items: [
        'Rose', 'Tulip', 'Daffodil', 'Sunflower', 'Dahlia',
        'Chrysanthemum', 'Lily', 'Orchid', 'Peony', 'Iris',
        'Lavender', 'Jasmine', 'Magnolia', 'Bluebell', 'Foxglove',
        'Primrose', 'Cowslip', 'Snowdrop', 'Crocus', 'Hyacinth',
        'Anemone', 'Poppy', 'Forget-me-not', 'Violet', 'Pansy',
        'Marigold', 'Zinnia', 'Cosmos', 'Aster', 'Delphinium',
        'Lupin', 'Hollyhock', 'Snapdragon', 'Phlox', 'Geranium',
        'Begonia', 'Impatiens', 'Pelargonium', 'Fuchsia', 'Hibiscus',
        'Bougainvillea', 'Wisteria', 'Clematis', 'Passionflower', 'Honeysuckle',
      ],
    },
    {
      id: 'mathematicians',
      name: 'Famous Mathematicians',
      items: [
        'Euclid', 'Archimedes', 'Pythagoras', 'Thales', 'Diophantus',
        'Fibonacci', 'Descartes', 'Pascal', 'Fermat', 'Newton',
        'Leibniz', 'Euler', 'Bernoulli', 'Gauss', 'Cauchy',
        'Riemann', 'Weierstrass', 'Cantor', 'Dedekind', 'Poincaré',
        'Hilbert', 'Minkowski', 'Gödel', 'Turing', 'von Neumann',
        'Shannon', 'Kolmogorov', 'Grothendieck', 'Weil', 'Serre',
        'Deligne', 'Atiyah', 'Conway', 'Ramanujan', 'Hardy',
        'Littlewood', 'Boole', 'De Morgan', 'Cayley', 'Sylvester',
        'Noether', 'Banach', 'Hausdorff', 'Möbius', 'Lobachevsky',
      ],
    },
  ],
}
